describe('template spec',  function () {
  beforeEach(function() {
    cy.fixture('registerUser').as('userData');
    cy.fixture('loginUser').as('loginUser');
    cy.fixture('incorrect').as('incorrectUser');
  });
  it('register user test', function() {
    cy.visit('https://automationexercise.com/')
    cy.get('.shop-menu > .nav > :nth-child(2) > a').should('be.visible')
    cy.get('.shop-menu > .nav > :nth-child(4) > a').click()
    cy.get('[data-qa="signup-name"]').type(this.userData.userName)
    cy.get('[data-qa="signup-email"]').type(this.userData.email)
    cy.get('[data-qa="signup-button"]').click()
    cy.get(':nth-child(1) > b').should('be.visible')
    cy.get(':nth-child(4) > .top').click()
    cy.get('[data-qa="name"]').type(this.userData.userName)
    cy.get('[data-qa="password"]').type(this.userData.password)
    cy.get('[data-qa="days"]').select(this.userData.day)
    cy.get('[data-qa="months"]').select(this.userData.month)
    cy.get('[data-qa="years"]').select(this.userData.year)
    cy.get(':nth-child(7) > label').click()
    cy.get(':nth-child(8) > label').click()
    cy.get('[data-qa="first_name"]').type(this.userData.firstName)
    cy.get('[data-qa="last_name"]').type(this.userData.lastName)
    cy.get('[data-qa="address"]').type(this.userData.address)
    cy.get('[data-qa="country"]').select(this.userData.country)
    cy.get('[data-qa="state"]').type(this.userData.state)
    cy.get('[data-qa="city"]').type(this.userData.city)
    cy.get('[data-qa="zipcode"]').type(this.userData.zipcode)
    cy.get('[data-qa="mobile_number"]').type(this.userData.phone)
    cy.get('[data-qa="create-account"]').click()
    cy.get('b').should('be.visible')
    cy.get('[data-qa="continue-button"]').click()
    cy.get(':nth-child(10) > a').should('be.visible')
    cy.get('.shop-menu > .nav > :nth-child(5) > a').click()
    cy.get('b').should('be.visible')
    cy.get('[data-qa="continue-button"]').click()
  })
  it('login user test', function(){
    cy.visit('https://automationexercise.com/')
    cy.get('.shop-menu > .nav > :nth-child(2) > a').should('be.visible')
    cy.get('.shop-menu > .nav > :nth-child(4) > a').click()
    cy.get('.login-form > h2').should('be.visible')
    cy.get('[data-qa="login-email"]').type(this.loginUser.email)
    cy.get('[data-qa="login-password"]').type(this.loginUser.password)
    cy.get('[data-qa="login-button"]').click()
    cy.get(':nth-child(10) > a').should('be.visible')
    cy.get('.shop-menu > .nav > :nth-child(5) > a').click()
    cy.get('b').should('be.visible')
  })
  it('incorrect login user test', function(){
    cy.visit('https://automationexercise.com/')
    cy.get('.shop-menu > .nav > :nth-child(2) > a').should('be.visible')
    cy.get('.shop-menu > .nav > :nth-child(4) > a').click()
    cy.get('.login-form > h2').should('be.visible')
    cy.get('[data-qa="login-email"]').type(this.incorrectUser.email)
    cy.get('[data-qa="login-password"]').type(this.incorrectUser.password)
    cy.get('[data-qa="login-button"]').click()
    cy.get('.login-form > form > p').should('be.visible')
  })
})
